### ISSUE TITLE
Please update to last angular version to avoid old compilation es2015/esm2015

### ISSUE THREAD

**Issue by genomedicsmarzoli** [filipows/angular-animations#136]
Please update to last angular version to avoid old compilation es2015/esm2015

**Comment by filipows** [comment]
The new version is available with the [0.15.0-beta.0](https://www.npmjs.com/package/angular-animations/v/0.15.0-beta.0) tag.
Would you be able to check it out?

btw. there's similar thread here: https://github.com/filipows/angular-animations/issues/107#issuecomment-1501357352

**Comment by ghost** [comment]
it works perfectly!! i'll waiting for official release
