### ISSUE TITLE
Scale on bounce animation not working

### ISSUE THREAD

**Issue by Flusinerd** [filipows/angular-animations#22]
Hello, I cannot get the scale option to work with the bounce animation:

I tried it via:
`bounceAnimation({scale: 0.5})`
Fails with:
`Argument of type '{ scale: number; }' is not assignable to parameter of type 'IAnimationOptions'.
  Object literal may only specify known properties, and 'scale' does not exist in type 'IAnimationOptions'. [2345]`

as well as:
`[@bounce]="{value: wrongInput, params:{scale: 0.5}}"`
Then the animation plays but, scale has no effect

Am I doing smth wrong?

**Comment by f4bio** [comment]
what gave you the idea of using `scale` for this animation? and followup: what is it supposed to do?
animation options are `anchor`, `duration`,  `delay` and `animateChildren`:
```
export interface IAnimationOptions {
    /**
     * Name of the animation anchor that will be used in a template
     */
    anchor?: string;
    /**
     * Duration in ms
     */
    duration?: number;
    /**
     * Delay in ms
     *
     * Default: 0
     */
    delay?: number;
    /**
     * This parameter can only be set in a component's decorator.
     * Cannot be set in a template.
     *
     * Whether children animation should run 'before', 'together' or 'after' animation.
     * When set to 'none' chldren are not animated.
     *
     * Default: 'together'
     */
    animateChildren?: 'before' | 'together' | 'after' | 'none';
}
```

maybe check out [demos@stackblitz](https://stackblitz.com/edit/angular-animations-lib-demo) or post your code (although doesn't seem like something to be put in github's _**issues**_ as `bounce` animation functionality works just fine)

**Comment by Flusinerd** [comment]
According to the readme under the section:
Available Animations and Parameters

It says that bounce has an additional param "scale" with a initial value of 1.05

That's why I thought I could use it to make the bounce not so "high"

**Comment by Flusinerd** [comment]
I have checked out the interface too. So I was wondering if it's a mistake in the docs or if I was missing something

**Comment by f4bio** [comment]
aaah... you're right of course, sorry!
maybe try like this:
`<div [@bounce]="{ value: '', params: { scale: 2.0 } }"></div>`
?
can't really test atm...
I hope I remember, so I will have a more in-depth look later

**Comment by f4bio** [comment]
I think I found the reason/a solution, see:
[pulseAnimation](https://github.com/filipows/angular-animations/blob/33cd68fe9c817060a6999384635876740c07cc9c/lib/attention-seekers/pulse.animation.ts#L18-L25) uses an extended options interface (which has all defaults plus an optional `scale` field).
this:
```
@Component({
  ....
  animations: [
    pulseOnEnterAnimation({scale: 5})
  ]
})
```

works fine. 
so I guess @filipows just haven't had the time or forgot to do the same for the bounce animations.
I'll PR it later!

**Comment by filipows** [comment]
Hi Guys,

Thank you for your input! You're right, it was my mistake in the docs: 
`scale` parameter applies to pulse animation not to bounce. I fixed the docs now.
