### ISSUE TITLE
No animation is show

### ISSUE THREAD

**Issue by fabdeceglia** [filipows/angular-animations#32]
Hi all,
I am starting using the library in my project.
Everythng is setup like described in the documentation (imports and dependencies), but when a try to use any of the animations, nothing happens, with no error in my console.

Can you please help me debugging the issue?

**Comment by filipows** [comment]
Hi @fabdeceglia ,

You can check out [existing Stackblitz with demo app](https://stackblitz.com/edit/angular-animations-lib-demo) and see if it helps. 
If it still doesn't, would you create an example of your project on Stackblitz? I'll try to help you.
