### ISSUE TITLE
Angular 8 peer dependency upgrade

### ISSUE THREAD

**Issue by andrewjrhill** [filipows/angular-animations#34]
Angular 8 was released on May 28th. Animations seem to be working fine on my side but I am getting an outdated dependency warning when installing via npm.

```
npm WARN angular-animations@0.0.9 requires a peer of @angular/animations@^6.0.0 but none is installed. You must install peer dependencies yourself.
```

ETA on official Angular 8 support?

**Comment by filipows** [comment]
Hi @andrewjrhill ,

I updated peer dependency to allow newer versions of @angular/animations, so once you install `0.0.10` the warning should be gone. 
I tested animations in demo-app with Angular 8 and everything seems fine. Let me know if you notice anything unexpected.

Cheers!

**Comment by andrewjrhill** [comment]
@filipows - Thank you! Much appreciated.
