### ISSUE TITLE
How to listen to animation end event

### ISSUE THREAD

**Issue by SuneethaYamani** [filipows/angular-animations#36]
How to detect  animation end event and enable another animation in sequence

**Comment by filipows** [comment]
Hi @SuneethaYamani ,

We have 2 callback methods for each animation in Angular: `start` and `done` which are being triggered at the beginning and at the end of animation respectively. It will look like that:

```html
<div 
    [@bounce]="animationState" 
    (@bounce.start)="animStart()" 
    (@bounce.done)="animEnd()">
</div>
```

and in your component:
```typescript
  animate() {
    this.animationState = !this.animationState;
  }

  animStart() {
    console.log('Animation Started');
  }

  animEnd() {
    console.log('Animation Ended');
  }
```
So you could use `done` callback to trigger another animation in your case.

Here's an [example on Stackblitz](https://stackblitz.com/edit/angular-animations-end-callback-demo?file=src/app/demo-main/demo-main.component.html) I've created for you.
