### ISSUE TITLE
Horizontal collapse

### ISSUE THREAD

**Issue by abelrgr** [filipows/angular-animations#38]
Is possible to set the "expand" and "collapse" animations in horizontal  direction?

**Comment by filipows** [comment]
Hi @abelrgr,
Not yet, for now it only works in a vertical direction, but it's a good idea to add that option to the library.

**Comment by abney317** [comment]
Would also like to see this added. Would definitely be a nice one

**Comment by filipows** [comment]
This has been now published in the [v0.11.0](https://github.com/filipows/angular-animations/releases/tag/v0.11.0)

**Comment by madmacc** [comment]
@filipows How can I install the latest version with this animation? See my issue: https://github.com/filipows/angular-animations/issues/137
