### ISSUE TITLE
How to continually repeat an animation?

### ISSUE THREAD

**Issue by jherman** [filipows/angular-animations#42]
Hi,

Just as the title states, how can I get an animation to continually repeat? For example getting an image to use that attention seeker flash.

Thanks!

**Comment by filipows** [comment]
Hi @jherman,

You could potentially use the animation `done` callback and trigger new animation when the previous is done.
Here's the [example in Stackblitz](https://stackblitz.com/edit/angular-animations-repeat-continuously?file=src/app/demo-main/demo-main.component.html)

**Comment by jherman** [comment]
Perfect. Thank you!
