### ISSUE TITLE
minor - typo 

### ISSUE THREAD

**Issue by jhanink** [filipows/angular-animations#43]
"bouncint" -> "bouncing"

https://github.com/filipows/angular-animations/tree/master/lib/bouncint-exits

by the way. Thank you for this utility lib.

also, how did you make your github profile image?

**Comment by filipows** [comment]
Hi @jhanink ,

Thank you for your comment. The typo is now fixed :wink: 

In regards to the profile image, it's just a black and white photo with some photoshop levels adjustments.
