### ISSUE TITLE
i want text bounce again and again

### ISSUE THREAD

**Issue by dineshmaths1** [filipows/angular-animations#46]
This  is my code. I want  Book Event text bounce again and again contentiously 

animations:[
    bounceOnEnterAnimation({anchor:'titlebounce'})
  ]  
`<h3  [@titlebounce]  > Book Event </h3>`
How to fix?

**Comment by filipows** [comment]
Hi @dineshmaths1 ,

you could potentially use the animation `done` callback and trigger new animation when the previous is done. 

Here's an [example in Stackblitz](https://stackblitz.com/edit/angular-animations-repeat-bounce-continuously?file=src%2Fapp%2Fdemo-main%2Fdemo-main.component.html)

**Comment by dineshmaths1** [comment]
Awesome
