### ISSUE TITLE
Angular 9 issue: could not resolve angular-animations relative to [object Object]

### ISSUE THREAD

**Issue by aford22** [filipows/angular-animations#52]
Hello,

I have just stumbled across your library and it looks amazing!

However I am using Angular 9 and am receiving an error in my code:

```
import { pulseAnimation } from 'angular-animations';

@Component({
  selector: 'app-credentials-dropdown',
  templateUrl: './credentials-dropdown.component.html',
  animations: [
    pulseAnimation()
  ]
```

The compile-time error is:
```
Error during template compile
could not resolve angular-animations relative to [object Object]
```

Any ideas? I am wondering if your library supports Angular 9.

Do note that if I stop "ng serve" and restart it, effectively recompiling the app, then this error goes away. However as soon as I then try to use an additional animation, the error comes back again, and I have to kill ng serve again.

So its not a showstopper - I am just worried that it might be a sign of something more sinister going on...

**Comment by filipows** [comment]
Hi @aford22, 
thanks for your kind message!

I have been successfully using the library with Angular 9 and Ivy for some time and I haven't faced any issues so far.

It might be related to how `ng serve` works, but I'll try to replicate your issue and investigate that.

**Comment by filipows** [comment]
Hi @aford22 ,

I was not able to replicate your issue. 
Does this problem still occur in the latest version?
