### ISSUE TITLE
Loop animations?

### ISSUE THREAD

**Issue by aford22** [filipows/angular-animations#53]
Hello,

I am trying to get one of your animations to continually loop. I.e. I want this icon button to continually pulse. But I can't get it to work - it doesnt pulse at all. Any ideas?

```
import { pulseAnimation } from 'angular-animations';

@Component({
  selector: 'app-credentials-dropdown',
  templateUrl: './credentials-dropdown.component.html',
  animations: [
    pulseAnimation()
  ]
})
```
and
```
    <button mat-icon-button [@pulse]="true">
        <mat-icon>add</mat-icon>
    </button>
```

**Comment by filipows** [comment]
Hi @aford22 ,

have a look at those 2 issues with Stackblitz examples: https://github.com/filipows/angular-animations/issues/42, https://github.com/filipows/angular-animations/issues/46

and let me know if that's what you're looking for.

**Comment by aford22** [comment]
Perfect! And yes it worked.

Perhaps it could be an enhancement request to add { repeat: true } to the pulseAnimation() method?

**Comment by filipows** [comment]
That sounds like a legit request, as you're not the first person trying to achieve the same thing. Unfortunately, till now I haven't figured out a way to achieve looping animations in Angular (it doesn't support `animation-iteration-count`) other than the mentioned workaround with the `done` callback :disappointed: 
There's some discussion about looping animations in here: https://github.com/angular/angular/issues/20621

If you have an idea how we could achieve this in a simpler way, I'm more than happy to discuss it.
