### ISSUE TITLE
Hide component before delay ends

### ISSUE THREAD

**Issue by macure** [filipows/angular-animations#58]
Hi,

is there a way that a component can be hidden before the delay ends. For example when using fadeIn with delay 3 sec?

I tried adding `opacity: 0; animation-fill-mode: forwards;` css properties to the component where animation is attached. Didn't work though ...

Thanks

**Comment by filipows** [comment]
Hi @macure,

The delay currently won't work with the `fadeIn` animation. 
I think it's worth to revisit fadeIn/fadeOut's animations so they would work with `delay` as you expect. 

That said, you can currently use `fadeInOnEnter` animation to have an element "hidden" before the delay ends.
Here's the [example in Stackblitz](https://stackblitz.com/edit/angular-animations-delayed-on-enter?file=src/app/demo-main/demo-main.component.html)

**Comment by filipows** [comment]
All the entrance animations have been fixed to make it possible to hide component before delay ends.
Fixed version `v0.11.0` has been published  to npm. 

Here is [example in StackBlitz](https://stackblitz.com/edit/angular-animations-delayed-fadein-fadeout?file=src%2Fapp%2Fdemo-main%2Fdemo-main.component.html)

**Comment by macure** [comment]
Thank you!
