### ISSUE TITLE
Is it possible to wait for first animation to end before the second one starts?

### ISSUE THREAD

**Issue by hassanasad** [filipows/angular-animations#60]
I have two screens that i need to fade in and out one after the other but not both of them together. Is it possible to detect if the first fade out was completed to trigger the second fade in ?

I have three screens in total. First two are conditional, I want them to fade in and out one after the other (but not both at the same time). Is it possible ? 

I apologize if i am not making any sense.

**Comment by hassanasad** [comment]
Basically Like this but not showing back images at the same time when button is toggled.
https://stackblitz.com/edit/angular-animations-delayed-on-enter-qgzkky?file=src%2Fapp%2Fdemo-main%2Fdemo-main.component.html

**Comment by filipows** [comment]
Hi @hassanasad ,

Thanks for your question. You can detect if the animation has finished with the `done` callback.
Here is the [example in Stackblitz](https://stackblitz.com/edit/angular-animations-delayed-on-enter-until-other-leave?file=src/app/demo-main/demo-main.component.html)

Let me know if that helps :slightly_smiling_face:

**Comment by hassanasad** [comment]
Thanks @filipows It does help.

P.S: I didn't find that event `done` in the readme. Maybe it would be quite helpful if all events are in the documentation :)

**Comment by filipows** [comment]
Hi @hassanasad,

It is a good idea to include some info about `start` and `done` animation callbacks in the readme :+1: 

They are part of the Angular framework. 
You can find more info about them [here](https://angular.io/guide/transition-and-triggers#animation-callbacks) or [here](https://angular.io/api/animations/AnimationEvent)

**Comment by hassanasad** [comment]
Oh - makes more sense now :)

**Comment by filipows** [comment]
The information about `start` and `done` callbacks has been added to the readme.
