### ISSUE TITLE
Can't build app

### ISSUE THREAD

**Issue by grungert** [filipows/angular-animations#66]
First great feature. Easy and fun to use :D 

I have a problem when I try to build an app. I have this error:

ERROR in src/app/page-content/overview/overview.component.ts(16,5): Error during template compile of 'OverviewComponent'
  Function calls are not supported in decorators but 'fadeInUpOnEnterAnimation' was called.

I'm using angular 8.2.0:
...
"@angular/forms": "^8.2.0",
"@angular/platform-browser": "^8.2.0",
"angular-animations": "^0.11.0",
...

In visual studio code, I have also error highlights. But when I again run:  npm i angular-animations --save the error is gone. But when I change one parameter error is back again. Here are screenshots:
![image](https://user-images.githubusercontent.com/20041837/94528530-d29f2000-0238-11eb-8858-f6022d4ed7a5.png)
img1 - when I run the install

![Untitled-1](https://user-images.githubusercontent.com/20041837/94528765-23af1400-0239-11eb-823c-6dc150906a56.jpg)
img2 - after I change one parameter

I saw in documentation that is working with AOT and JIT compilations.

Can you provide me suggestions to the problem?

**Comment by filipows** [comment]
Hi @grungert,
It's an interesting issue, thanks for posting it. Is this error shown only in VS Code or during the build of the application (`ng build` output) as well?

The animation functions used in the decorator are statically analyzable and after the compilation the errors should be gone.

**Comment by grungert** [comment]
It is showing on ng build on the server. And the same situation on other computers inside the team. Here is the output error from build (it is also in the first post): 
ERROR in src/app/page-content/overview/overview.component.ts(16,5): Error during template compile of 'OverviewComponent'
Function calls are not supported in decorators but 'fadeInUpOnEnterAnimation' was called.

**Comment by Marcelh1983** [comment]
Weird issue. When I open vscode it gives me the same errors. When I do an aot build, it succeeds and vscode isn't giving me this errors anymore.

**Comment by grungert** [comment]
@Marcelh1983 thank you for the replay. It is a weird issue. I try to build it with AOT and I got the same error.

**Comment by grungert** [comment]
@filipows is there any news about this issue?

**Comment by filipows** [comment]
Hi @grungert,

I haven't had much time to investigate the issue yet. I have seen the error in the VSCode, but as soon as I compile the app (I run`ng build`), the error disappears. And in my case, the error never caused the compilation to fail. 

Have you found any workaround for your build so far? 

I might need to create a small demo with reproduction first - would you like to help with that?

**Comment by Marcelh1983** [comment]
@grungert translate is not a field of IAnimationOptions. Could that be the issues while compiling?

**Comment by grungert** [comment]
@Marcelh1983 and @filipows I'm not sure. Anyway, I update angular to 10.1.4 and on that version everything is fine. The build is running fine bout for --aot and --prod.

**Comment by eldhose-cavli** [comment]
downgrade version to 0.0.10, it's works for me
`"angular-animations": "^0.0.10",`
