### ISSUE TITLE
How to animate something inside of an ngIf?

### ISSUE THREAD

**Issue by saffabook** [filipows/angular-animations#82]
Hi there, I have a looping animation on an icon. 

`<button *ngIf="showSave"><icon="star" [@bounce]="animState" (@bounce.done)="animDone()"><icon> Save</button>`

There is an **icon** is inside of a button to draw attention. But I want to hide that button until some event completes. 

When the event is complete, I want to show the save button ie ***ngIf="showSave"** however the icon does not animate. 

If I take the `<icon>` outside of the ***ngIf**, it works. How would one achieve this?

**Comment by MickL** [comment]
This question is not related to filipows/angular-animations and has been answered here for example: https://indepth.dev/posts/1285/in-depth-guide-into-animations-in-angular#animating-children-elements

Add the following animation:
```ts
trigger('container', [
		transition(':enter, :leave', [
			query('@*', animateChild()),
		]),
	]),
```

Now add `@container` to your button an voilá!

**Comment by saffabook** [comment]
Thank you
